; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[backgroundfield][version] = "1.5"

projects[ctools][version] = "1.3"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[features][version] = "2.0-rc3"

projects[google_fonts][version] = "2.3"

projects[jquery_update][version] = "2.3"

projects[pathauto][version] = "1.2"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

; Themes
projects[rubik][version] = "4.0-beta9"

projects[tao][version] = "3.0-beta4"

; Others

projects[manhattanville_features][download][type] = "get"
projects[manhattanville_features][download][url] = "http://purplescripts.net/manhattanville.zip"
projects[manhattanville_features][type] = "module"

projects[manhattanville][download][type] = "get"
projects[manhattanville][download][url] = "http://purplescripts.net/manhattanville_features.zip"
projects[manhattanville][type] = "theme"