; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Profile
projects[manhattanville_profile][type] = "profile"

projects[manhattanville_profile][download][type] = "local"

projects[manhattanville_profile][download][source] = lib/profiles/manhattanville_profile

; Modules
projects[auto_nodetitle][version] = "1.0"

projects[ctools][version] = "1.3"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[features_extra][version] = "1.0-beta1"

projects[features][version] = "2.0-rc3"

projects[media][version] = "1.3"

projects[footer_message][version] = "1.1"

projects[google_fonts][version] = "2.3"

projects[jquery_update][version] = "2.3"

projects[pathauto][version] = "1.2"

projects[strongarm][version] = "2.0"

projects[styleguide][version] = "1.1"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

projects[webform][version] = "3.19"

; Themes

projects[rubik][version] = "4.0-beta9"

projects[tao][version] = "3.0-beta4"

; Others

 projects[manhattanville_features][download][type] = "local"
 projects[manhattanville_features][download][source] = lib/modules/manhattanville_features
 projects[manhattanville_features][type] = "module"

 projects[block_manhattanville][download][type] = "local"
 projects[block_manhattanville][download][source] = lib/modules/block_manhattanville
 projects[block_manhattanville][type] = "module"

 projects[manhattanville][download][type] = "local"
 projects[manhattanville][download][source] = lib/themes/manhattanville
 projects[manhattanville][type] = "theme"

