; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[ctools][version] = "1.3"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[features][version] = "2.0-rc3"

projects[jquery_update][version] = "2.3"

projects[strongarm][version] = "2.0"

projects[views][version] = "3.7"

; Themes
projects[bootstrap][version] = "2.1"

projects[rubik][version] = "4.0-beta9"

projects[tao][version] = "3.0-beta4"

; Modules
projects[manhattanville][type] = "module"
projects[manhattanville][download][type] = "git"
projects[manhattanville][download][url] = "https://github.com/dismorfo/manhattanville.git"
projects[manhattanville][download][revision] = "321c30a427b94334f2db539fcddfad8f688e4c28"

