<?php

function mville_team_players() {
  require_once('dummy_content.inc');

  return array(
    array(
      'title' => filter_xss('Renzo Piano'),
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'field_team' => 'Design Team',
      'field_organization' => 'Renzo Piano Building Workshop',
      'photo' => 'piano.jpg',
      'field_profile' => filter_xss("<p>Born in Beirut, Chaaya is a graduate of Kaslik Saint-Esprit University. He joined the Paris office of Renzo Piano Building Workshop in 1988 and has worked as lead architect on a variety of projects including the Kanak Cultural Center in New Caledonia and the Potsdamer Platz project in Berlin. In 1997, he became a partner at RPBW. He was partner-in-charge of the new Il Sole 24 Ore headquarters in Milan and is now in charge of the Los Angeles County Museum of Art expansion project and phase one of ColumbiaÕs proposed Manhattanville urban academic community."),
    ),

    array(
      'title' => filter_xss('Antoine Chaaya'),
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'field_team' => 'Design Team',
      'field_organization' => 'Renzo Piano Building Workshop',
      'photo' => 'chaaya.jpg',
      'field_organization' => 'Renzo Piano Building Workshop',
      'field_profile' => filter_xss("<p>Renzo Piano is the founder of Renzo Piano Building Workshop, an architectural firm with offices
                          in Paris and Genoa. Before starting RPBW in 1993, he founded the Piano & Rogers agency with Richard
                          Rogers in 1971 and l'Atelier Piano & Rice with engineer Peter Rice in 1977. RPBW has designed a number
                          of venues and buildings around the world including the reconstruction of the Potsdamer Platz in Berlin.
                          They are currently the architects of the new headquarters for the New York Times and Morgan Library addition
                          in Manhattan and were recently commissioned as the architects for the London Bridge Tower. His firm has
                          garnered several prestigious architectural honors, including the Pritzker Architecture Prize in 1998. He
                          graduated in 1964 from the school of Architecture of the Milan Polytechnic.</p>"),
    ),

    array(
      'title' => filter_xss('Anthony Vacchione'),
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'photo' => 'vacchione.jpg',
      'field_team' => 'Design Team',
      'field_profile' => filter_xss("<p>Vacchione joined SOM in 1978 and was named a Managing Partner in 1999. In addition to being involved
                         in ongoing strategic campus planning for Columbia University since the SOM's work on the East Campus
                         Master Plan in the early 1990s, Vacchione has managed many of SOM's major planning and design projects,
                         including major airport terminals and terminal expansions at JFK, Newark, Boston Logan, Toronto, and
                         Singapore Changi airports; Riverside South, the East River Master Plan, the Tzu Chi Cultural Campus in
                         Hualien, Taiwan; and the Columbia-Presbyterian Medical Center (now the Columbia University Medical
                         Center). He received a master of architecture degree from Columbia University.</p>"),
      'field_organization' => 'Skidmore, Owings and Merrill',
    ),

    array(
      'title' => filter_xss('James Corner'),
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'photo' => 'corner.jpg',
      'field_team' => 'Design Team',
      'field_profile' => filter_xss("<p>James Corner is a registered landscape architect and urban designer, and director of Field Operations,
                          an internationally recognized landscape architecture and urban design practice based in New York City.
                          Corner is also chair and professor in the Department of Landscape Architecture and Regional Planning
                          at the University of Pennsylvania School of Design. Field Operations is presently directing the design
                          of the High Line, a 1.5-mile-long elevated promenade along the west side of Manhattan; Fresh Kills Park,
                          Staten Island; and a variety of other major public open spaces in New York. Other projects include large
                           parks, urban redevelopment plans and public spaces in Toronto, London, Seoul, San Juan and Busan, South
                           Korea. Corner's work has been recognized with numerous awards: the NYC Arts Commission Award for
                           Excellence in Design (2005), the American Academy of Arts and Letters Academy Award in
                           Architecture (2004), the Daimler-Chrysler Award for Design Innovation (2000) and the
                           Architectural League of New York Design Award (2000).</p>"),
      'field_organization' => 'Field Operations',
    ),

    array(
      'title' => filter_xss('La-Verna Fountain'),
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'photo' => 'fountain.jpg',
      'field_profile' => filter_xss("<p>La-Verna Fountain currently serves as the Vice President for Construction Business Services
                          and Communications at Columbia University in the City of New York. As the Vice President,
                          Ms. Fountain will help lead our outreach and communications efforts regarding construction
                          business opportunities and activities.</p><p>Prior to assuming the role in Facilities, Ms.
                          Fountain served as the Associate Vice President of Public Affairs where she served as the Chief
                          Operating Officer of Columbia's Office of Communications and Public Affairs and as the public
                          affairs liaison on the University's top initiativeâ the expansion of the University.</p>
                          <p>In addition to her work at the University, Ms. Fountain is the President and founder of the
                          Defiant Hope Consulting and Training Company. For the past 25 years, she has provided motivational
                          speeches, training and facilitation on topics of conflict resolution, cultural diversity/human awareness,
                          nonviolence as a way of life, working with teenagers, spirituality in the workplace, staff development
                          and organizational development.</p><p>La-Verna also served as the Director of Communications for the
                          Pennsylvania Department of Education, Senior Advisor to Save the Children for its U.S. programs,
                          served as the State Office Director for former U.S. Senator Harris Wofford, and as Deputy Communications
                          Director for the late Pennsylvania Governor Robert P. Casey.</p>"),
      'field_team' => 'Columbia Project Team',
      'field_organization' => 'Columbia University, Facilities',
    ),

    array(
      'title' => filter_xss('Maxine F. Griffith'),
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'photo' => 'griffith.jpg',
      'field_team' => 'Columbia Project Team',
      'field_profile' => filter_xss("
                         <p>Maxine Griffith is Executive Vice President for Government and Community Affairs at Columbia and Special Advisor for Campus Planning. She is responsible for the oversight and coordination of the University's collaborations with government at the local, state, and federal levels, as well as the strengthening of Columbia's many partnerships with local organizations.</p>
                         <p>From 2000 to 2005, Griffith served as Executive Director of the Philadelphia City Planning Commission and as that city's Secretary (Deputy Mayor) for Strategic Planning. Previously, Griffith served in the Clinton administration at the U.S. Department of Housing and Urban Development as Regional Representative for New York and New Jersey and as Assistant Deputy Secretary. From 1988 to 1996, she was Principal of Griffith Planning & Design, a firm providing planning, urban design, and development services.</p>
                         <p>Griffith has also served on the New York City Planning Commission and currently sits on the boards of the Architectural League of New York, the Regional Plan Association, and Seeds, an organization building schools and libraries in West Africa.</p>
                         <p>Griffith was born in Harlem, graduated cum laude from Hunter College, and holds a master's degree in architecture from the University of California, Berkeley. She has taught city planning and urban design at Columbia, New York University, and the University of Pennsylvania and is an accredited member of the American Institute of Certified Planners.</p>
      "),
      'field_organization' => 'Office of Government and Community Affairs',
    ),

    array(
      'title' => filter_xss('Joe Ienuso'),
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'field_team' => 'Columbia Project Team',
      'photo' => 'ienuso.jpg',
      'field_team' => 'Columbia Project Team',
      'field_profile' => filter_xss("<p>Ienuso is the Executive Vice President for CU Facilities, having joined Columbia in 1989 and having held a number of senior administrative roles in Admissions, Financial Aid, Student Services, and Facilities Management. As part of the Facilities Management Executive Team since 2001, he well understands the Facilities agenda and is currently responsible for facilities operations, security, design and construction, and planning services for the Morningside Heights campus. Ienuso holds a B.S. and an M.S. from St. John's University and an M.B.A. from Columbia Business School.</p>"),
      'field_organization' => 'Columbia University, Facilities',
    ),

    array(
      'title' => filter_xss('Victoria Mason-Ailey'),
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'field_team' => 'Columbia Project Team',
      'photo' => 'mason-ailey.jpg',
      'field_team' => 'Columbia Project Team',
      'field_profile' => filter_xss("
                         <p>Mason-Ailey is the Assistant Vice President for Planning and Project Coordination within the Office of
                         Government and Community Affairs. She is charged with the coordination and communication of urban planning
                         and development matters; in particular those activities associated with the University's proposed campus
                         expansion into Manhattanville. Her work requires that she maintain frequent contact with community leaders
                         and public officials, as well as University officials, staff, and consultants. In addition, her activities
                         extend from initiatives on the Morningside campus to those of the Medical Center in Upper Manhattan.</p>
                         <p>Trained as an urban planner, with a master's degree in urban planning from Columbia and 20-plus years
                         of experience, Mason-Ailey has participated in a range of interagency, as well as public and private,
                         planning initiatives in several major cities, including New York and Philadelphia.</p>
                         <p>She holds a bachelor's degree from Brown University and is professionally certified by the American
                         Institute of Certified Planners.</p>
      "),
      'field_organization' => 'Office of Government and Community Affairs',
    ),

    array(
      'title' => filter_xss('Philip Pitruzzello'),
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'field_team' => 'Columbia Project Team',
      'photo' => 'pitruzzello.jpg',
      'field_team' => 'Columbia Project Team',
      'field_profile' => filter_xss("
                         <p>Pitruzzello is the Vice President for Manhattanville Development. He serves as the Columbia University Facilities point person on all aspects of the development, design and construction of the University's 6.8 million sq. ft. Manhattanville in West Harlem campus expansion.</p>
                         <p>Previously, he was Vice President for Real Estate at Time Warner, where he was responsible for corporate real estate, design and project management, and operations. He led Time Warner's team in the planning, design, and construction of the company's one million square foot office, broadcast center and corporate headquarters interiors within Time Warner Center in New York City.</p>
                         <p>Prior to joining Time Warner, Pitruzzello was a partner in a real estate banking firm and served with the Battery Park City Authority in several senior management capacities including President and Chief Executive Officer, at a time when the 92-acre Battery Park City project became a thriving office, residential, and retail community.</p>
                         <p>Earlier in his career, Pitruzzello specialized in finance and construction law in the fields of affordable housing, health care, and higher education. He has also served as Assistant Counsel to former New York Gov. Mario M. Cuomo and was general counsel to several public benefit corporations.<p>Additionally, he is a director of New Yorkers for Parks, a director of the Bowery Residents Committee and the Apollo Theater Foundation, and a member of the Urban Land Institute. He received a B.A. from the University of Chicago and a J.D. from Boston University.</p>")
      ,
      'field_organization' => 'Columbia University, Manhattanville Development',
    ),

    array(
      'title' => filter_xss('Marcelo Velez'),
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'field_team' => 'Columbia Project Team',
      'photo' => 'velez.jpg',
      'field_team' => 'Columbia Project Team',
      'field_profile' => filter_xss("
	                     <p>Marcelo Velez is Associate Vice President for Manhattanville Capital Construction in Columbia University Facilities. He is a professional engineer with almost 20 years of diverse construction project management experience. Velez has a record of accomplishments in managing large and complex construction projects through the planning, design, and construction phases. Over the years, he has managed, supervised, and otherwise presided over $1 billion worth of capital construction. His recent projects include the Columbia University School of Social Work, 2700 Broadway, the School at 110th Street, Lenfest Hall, Broadway Residence, and the renovation of River Hall.</p>
      "),
      'field_organization' => 'Columbia University, Manhattanville Capital Construction',
    ),

    array(
      'title' => filter_xss('Geoffrey R. Wiener Jr.'),
      'photo' => 'wiener.jpg',
      'language' => LANGUAGE_NONE,
      'type' => 'team',
      'field_team' => 'Columbia Project Team',
      'field_profile' => filter_xss("
	                     <p>Weiner heads Columbia's Facilities Planning and Space Management group, which is responsible for developing solutions to space problems ranging from how to free up an office for a new administrator, to where and how to create a third major campus. He and his staff are constantly responding to requests for new space from schools, departments, centers, institutes, administrative units, and related entities at the Morningside campus. As a land use planner, Weiner works on rezoning, zoning variances,
	                     and other discretionary land use approvals for Columbia properties.</p>
	                     <p>Before joining Columbia in 1984, he was a partner in a planning and development consulting firm in New York City, Abeles Schwartz Associates, which specialized in market, environmental, and economic feasibility analyses for new projects, subsidized housing development, and
	                     procurement of zoning and other land use approvals.</p>
	                     <p>Wiener received a B.A. in urban geography from Clark University in 1975 and a master's of city and regional planning from Pratt Institute in 1978. He serves on the boards of Hamilton Madison House, a social services agency on the Lower East Side, and the Interchurch Center, a nonprofit office
	                     building located near Columbia's main campus.</p>
      "),
      'field_organization' => 'Assistant Vice President for Facilities Planning, Columbia University',
    ),
  );
}
